FROM  ubuntu:22.04

RUN apt update
RUN apt install nginx -y

ADD index.html /var/www/html
ADD index_tar.tar.gz /var/www/html

EXPOSE 80

CMD [ "/usr/sbin/nginx", "-g", "daemon off;" ]


# tar -czvf index_tar.tar.gz index_tar
# sudo docker build -t nginx_image:1.0 .
# sudo docker images
# sudo docker run -d -it --name nginx_container -p 8000:80 nginx_image:1.0
# sudo docker ps -a